name: Git Town

on:
  pull_request:
    branches:
      - "**"

jobs:
  git-town:
    name: Display the branch stack
    runs-on: ubuntu-latest
    if: github.base_ref != 'main' || github.head_ref != 'dev'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: git-town/action@v1
